# coding: utf-8
"""jiuwen-glue — openJiuwen 胶水层最小实现（WO-0003 + M0.5 返工补齐）.

原生没有的能力（PROP-0001 v1.6 §0 总则 4 / §4.1；v1.7 §12.5 JIT 身份三件）:
- Budget Lease（预算租约：发放/占用/过期 + 级联撤销 + 签发时固化权限交集）→ :mod:`jiuwen_glue.leases`
- Evidence 三态（draft / verified / finalized）                          → :mod:`jiuwen_glue.evidence`
- 能力元数据注册（五类机读声明 + 版本准入 + 指标单向回流）               → :mod:`jiuwen_glue.capabilities`
- 协同三铁律的执行与检测                                                 → :mod:`jiuwen_glue.rules`
- GuardrailRun 门控协议聚合薄层（五步链路 + 聚合三态 fail-closed）       → :mod:`jiuwen_glue.guardrail`
- 三层复合身份 + 权限交集公式（研发手册原则一/二）                       → :mod:`jiuwen_glue.identity`
- Challenge 结构化对象（授权三态第三态）                                 → :mod:`jiuwen_glue.challenge`
- 记忆晋升管线（个人→组织资产晋升：质量门+脱敏门+版本化，不回写执行面）  → :mod:`jiuwen_glue.promotion`
- 决策记录（append-only）                                                → :mod:`jiuwen_glue.decisions`
- 产物路由表 + 节点容量模型（便宜三件 Python 侧）                        → :mod:`jiuwen_glue.routes`
- 决策层 MVP（JevProvider 三原语：classify/score/judge + 决策留痕）      → :mod:`jiuwen_glue.decision`
- 消融验证（WO-0007 件 1：准入前 A/B 对照，原生没有对照实验）            → :mod:`jiuwen_glue.ablation`
- 准入记录（WO-0007 件 2：消融+GuardrailRun 硬规则，绑定 Spec 版本）     → :mod:`jiuwen_glue.admission`
- usage_events 计量四维度 + 租约-Higress consumer 绑定（断流求值）       → :mod:`jiuwen_glue.usage`
- 升级阶梯状态机 L0-L5 + 人类就绪包四件套（v2.1 §4.7）                  → :mod:`jiuwen_glue.escalation`
- 计费 P0：internal 按 project 归集 + 影子成本周报 + 费率卡确定性结算骨架 → :mod:`jiuwen_glue.billing`
- 平台 token 铸造器（TTL≤1h/禁缓存禁代签/decided_by 留痕，v2.1 §4.5）   → :mod:`jiuwen_glue.platform_tokens`

边界（写死）: 原生层管"怎么做"，glue 管"准不准进"，控制台管"看得见"；
发现与编排一律用原生 Symphony，本包不自建发现机制；
**glue 不新增第二个决策点**（GuardrailRun 聚合 verdict 是唯一门控输出）。
"""
from .ablation import (
    ABLATION_VERDICTS,
    VERDICT_IMPROVED,
    VERDICT_INCONCLUSIVE,
    VERDICT_NEUTRAL,
    VERDICT_REGRESSED,
    AblationArm,
    AblationError,
    AblationExperiment,
    AblationResult,
    PairScore,
    sign_test_p,
)
from .admission import (
    ADMISSION_DECISIONS,
    DECISION_ALLOWED,
    DECISION_HELD,
    DECISION_REJECTED,
    AdmissionError,
    AdmissionLedger,
    AdmissionRecord,
    export_to_skillpack,
    guardrail_verdict_of,
)
from .capabilities import (
    ADMITTED,
    CANDIDATE,
    REJECTED,
    CapabilityDeclaration,
    CapabilityRegistry,
    CapabilityVersion,
)
from .challenge import (
    APPROVED,
    CONFIRM_DUTY_OFFICER,
    CONFIRM_RESOURCE_OWNER,
    CONFIRM_USER,
    DENIED,
    EXPIRED as CHALLENGE_EXPIRED,
    PENDING as CHALLENGE_PENDING,
    Challenge,
    ChallengeBoard,
)
from .decision import (
    PRIMITIVES,
    PRIMITIVE_CLASSIFY,
    PRIMITIVE_JUDGE,
    PRIMITIVE_SCORE,
    SCORE_RUBRIC_PROMOTION,
    DecisionLayer,
    DecisionLayerError,
    JevBackend,
    JevBackendError,
    JevProvider,
    ModelBackend,
    PrimitiveOutcome,
    RefusalRecord,
    RuleBasedBackend,
    make_score_hook,
)
from .decisions import DecisionLog, DecisionRecord, context_hash
from .escalation import (
    HARD_IRREVERSIBLE,
    HARD_LEGAL_TOS,
    HARD_LIST,
    HARD_MONEY,
    HARD_THEORY_APPROVAL,
    LEVELS,
    LEVEL_CAPABILITIES,
    LEVEL_L0,
    LEVEL_L1,
    LEVEL_L2,
    LEVEL_L3,
    LEVEL_L4,
    LEVEL_L5,
    LEVEL_ROLE,
    PIECE_CATEGORY,
    PIECE_FACTS,
    PIECE_KEYS,
    PIECE_NO_SOLUTION,
    PIECE_REVERSIBILITY,
    PROOF_LEVELS,
    SCOPE as ESCALATION_SCOPE,
    Escalation,
    EscalationCase,
    EscalationEvent,
    EscalationLedger,
    EscalationRequiredError,
    EscalationSchemaError,
    EscalationStateError,
    EscalationStormError,
    FrozenFact,
    PermissionExpansionProposal,
    ReadinessPackage,
    ReadinessPiece,
    ReadinessTask,
    ReversibilityAssessment,
    StormGuard,
    UnknownEscalationCaseError,
    render_readiness,
    signature_for,
)
from .errors import (
    AdmissionDeniedError,
    ArtifactRouteUndeclaredError,
    BillingError,
    BillingSchemaError,
    BillingSettleError,
    BudgetExceededError,
    CapacitySchemaError,
    ChallengeStateError,
    DecisionSchemaError,
    DeclarationSchemaError,
    DelegationScopeError,
    EvidenceImmutableError,
    GuardrailSchemaError,
    GuardrailStateError,
    IdentitySchemaError,
    IllegalTransitionError,
    IronRuleViolation,
    LeaseDerivationError,
    LeaseExhaustedError,
    LeaseExpiredError,
    LeaseRevokedError,
    MissingTaskReferenceError,
    PromotionTransitionError,
    RouteSchemaError,
    Rule1MessageIsNotClaim,
    Rule2ConversationIsNotState,
    Rule3InternalStepIsNotTask,
    UnknownCapabilityError,
    UnknownChallengeError,
    UnknownDecisionError,
    UnknownGuardrailRunError,
    UnknownPromotionAssetError,
    UsageError,
    UsageSchemaError,
    UsageStateError,
)
from .evidence import DRAFT, FINALIZED, VERIFIED, Evidence, EvidenceStore, EvidenceTransition
from .guardrail import (
    BACKEND_EVAL_GATE,
    BACKEND_NATIVE_GUARDRAIL,
    BACKEND_PERMISSION_RAIL,
    BACKEND_SCAN,
    OUTCOME_ASK,
    OUTCOME_BLOCKED,
    OUTCOME_PASS,
    OUTCOME_UNKNOWN,
    RUN_FINALIZED,
    RUN_OPEN,
    RUN_VOID,
    VERDICT_BLOCKED,
    VERDICT_PASS,
    VERDICT_UNKNOWN,
    CheckResult,
    CheckSpec,
    GuardrailResult,
    GuardrailRun,
    GuardrailRunStore,
    GuardrailSpec,
    aggregate,
)
from .identity import (
    AGENT_CAPS,
    DELEGATION,
    PLATFORM_POLICY,
    RUNTIME,
    USER,
    AgentIdentity,
    Delegation,
    EffectivePerms,
    RunInstance,
    TaskContext,
    composite_ref,
    effective_permissions,
    narrow_delegation,
)
from .leases import ACTIVE, EXHAUSTED, EXPIRED, REVOKED, BudgetLedger, BudgetLease
from .billing import (
    RATE_CARD_SCHEMA,
    SETTLE_ENGINE,
    UNATTRIBUTED_LABEL,
    BillLine,
    ProjectUsage,
    UsageAggRow,
    UsageEventRow,
    RateCard,
    RateCardLine,
    SettlementResult,
    ShadowPrice,
    ShadowPriceTable,
    aggregate_by_project,
    bill_markdown,
    deterministic_settle,
    parse_rate_card,
    rate_card_snapshot_hash,
    select_rate_card,
    settlement_to_json,
    verify_rate_card,
    weekly_report,
)
from .platform_tokens import (
    BAO_REF_PREFIX,
    PLATFORMS,
    STATUS_ACTIVE,
    STATUS_EXPIRED,
    STATUS_REVOKED,
    TOKEN_TTL_CAP_SECONDS,
    GITHUB_JWT_TTL_CAP_SECONDS,
    ESCALATION_KIND,
    GitHubAppInstallationFlow,
    HardListEscalationError,
    MintedToken,
    PlatformTokenMinter,
    TokenMintError,
    TokenRequest,
    escalation_signal,
    hard_list_readiness,
)
from .promotion import (
    GATE_BLOCKED,
    GATE_PASS,
    GATE_UNKNOWN,
    STAGE_PROMOTED,
    STAGE_REJECTED,
    STAGE_SHORTLIST,
    STAGE_WITHDRAWN,
    STAGE_WORKING,
    PromotionCandidate,
    PromotionLedger,
    PromotionTransition,
)
from .routes import (
    KIND_CODE,
    KIND_EVAL,
    KIND_VIDEO,
    PIPELINE_DEFAULT,
    SINK_EVAL_ASSETS,
    SINK_GIT,
    SINK_MINIO,
    TRUST_TRUSTED,
    TRUST_UNTRUSTED,
    ArtifactRoute,
    ArtifactRouteTable,
    NodeCapacity,
)
from .usage import (
    BINDING_ACTIVE,
    BINDING_CUTOFF,
    BINDING_REVOKED,
    BINDING_STATES,
    CUTOFF_DRY_RUN,
    CUTOFF_ENFORCE,
    CUTOFF_MODES,
    KIND_COMPUTE_SECONDS,
    KIND_LLM_RELAY,
    KIND_SANDBOX_SECONDS,
    KIND_STORAGE_BYTES,
    REASON_LEASE_EXPIRED,
    REASON_LEASE_LAPSED,
    REASON_LEASE_REVOKED,
    SETTLEMENT_CLASSES,
    SETTLEMENT_CUSTOMER,
    SETTLEMENT_FREE,
    SETTLEMENT_INTERNAL,
    SETTLEMENT_TRIAL,
    USAGE_KINDS,
    BindingLedger,
    CutoffAction,
    LeaseConsumerBinding,
    UsageEvent,
    UsageLedger,
    UsageSummary,
    cutoff_due,
    cutoff_plan,
)
from .rules import (
    BLOCKED,
    CANCELLED,
    CLAIMED,
    COMPLETED,
    PENDING,
    MessageReceipt,
    SubtaskSpec,
    Task,
    TaskLedger,
)
from .selection import (
    MAX_CANDIDATES,
    SCOPE as SELECTION_SCOPE,
    SIGNALS as SELECTION_SIGNALS,
    SIGNAL_WEIGHTS,
    SIGNAL_BUDGET,
    SIGNAL_CONCISENESS,
    SIGNAL_DIFF_CONSENSUS,
    SIGNAL_EVAL,
    SIGNAL_MUTATION,
    Candidate as SelectionCandidate,
    SelectionError,
    SelectionRejectedError,
    SelectionResult,
    score as selection_score,
    select as select_winner,
)

__version__ = "0.2.0"

__all__ = [
    # errors
    "IronRuleViolation",
    "Rule1MessageIsNotClaim", "Rule2ConversationIsNotState", "Rule3InternalStepIsNotTask",
    "BudgetExceededError", "LeaseDerivationError", "LeaseExhaustedError",
    "LeaseExpiredError", "LeaseRevokedError",
    "IllegalTransitionError", "EvidenceImmutableError",
    "DeclarationSchemaError", "AdmissionDeniedError", "UnknownCapabilityError",
    "MissingTaskReferenceError",
    "DelegationScopeError", "GuardrailSchemaError", "GuardrailStateError",
    "IdentitySchemaError",
    "UnknownGuardrailRunError", "ChallengeStateError", "UnknownChallengeError",
    "PromotionTransitionError", "UnknownPromotionAssetError",
    "DecisionSchemaError", "UnknownDecisionError",
    "ArtifactRouteUndeclaredError", "RouteSchemaError", "CapacitySchemaError",
    "DecisionLayerError", "JevBackendError", "AblationError", "AdmissionError",
    "UsageError", "UsageSchemaError", "UsageStateError",
    # leases
    "BudgetLedger", "BudgetLease",
    "ACTIVE", "EXHAUSTED", "EXPIRED", "REVOKED",
    # evidence
    "Evidence", "EvidenceStore", "EvidenceTransition",
    "DRAFT", "VERIFIED", "FINALIZED",
    # capabilities
    "CapabilityDeclaration", "CapabilityRegistry", "CapabilityVersion",
    "CANDIDATE", "ADMITTED", "REJECTED",
    # rules
    "Task", "TaskLedger", "MessageReceipt", "SubtaskSpec",
    "PENDING", "CLAIMED", "COMPLETED", "BLOCKED", "CANCELLED",
    # guardrail（聚合三态 = 唯一门控输出）
    "GuardrailSpec", "CheckSpec", "CheckResult", "GuardrailRun", "GuardrailRunStore",
    "GuardrailResult", "aggregate",
    "BACKEND_NATIVE_GUARDRAIL", "BACKEND_PERMISSION_RAIL", "BACKEND_EVAL_GATE", "BACKEND_SCAN",
    "VERDICT_PASS", "VERDICT_BLOCKED", "VERDICT_UNKNOWN",
    "OUTCOME_PASS", "OUTCOME_BLOCKED", "OUTCOME_UNKNOWN", "OUTCOME_ASK",
    "RUN_OPEN", "RUN_FINALIZED", "RUN_VOID",
    # identity（三层复合身份 + 权限交集公式）
    "AgentIdentity", "RunInstance", "TaskContext", "Delegation",
    "composite_ref", "effective_permissions", "EffectivePerms", "narrow_delegation",
    "USER", "AGENT_CAPS", "PLATFORM_POLICY", "DELEGATION", "RUNTIME",
    # challenge（授权三态第三态）
    "Challenge", "ChallengeBoard",
    "CHALLENGE_PENDING", "CHALLENGE_EXPIRED",
    "APPROVED", "DENIED",
    "CONFIRM_USER", "CONFIRM_RESOURCE_OWNER", "CONFIRM_DUTY_OFFICER",
    # promotion（记忆晋升管线）
    "PromotionLedger", "PromotionCandidate", "PromotionTransition",
    "STAGE_WORKING", "STAGE_SHORTLIST", "STAGE_PROMOTED", "STAGE_REJECTED", "STAGE_WITHDRAWN",
    "GATE_PASS", "GATE_BLOCKED", "GATE_UNKNOWN",
    # decisions（决策记录，append-only）
    "DecisionLog", "DecisionRecord", "context_hash",
    # decision（决策层 MVP：JevProvider 三原语，WO-0010）
    "DecisionLayer", "JevProvider", "JevBackend", "RuleBasedBackend", "ModelBackend",
    "PrimitiveOutcome", "RefusalRecord", "make_score_hook",
    "PRIMITIVE_CLASSIFY", "PRIMITIVE_SCORE", "PRIMITIVE_JUDGE", "PRIMITIVES",
    "SCORE_RUBRIC_PROMOTION",
    # ablation（WO-0007 件 1：消融验证）
    "AblationArm", "AblationExperiment", "AblationResult", "PairScore", "sign_test_p",
    "VERDICT_IMPROVED", "VERDICT_NEUTRAL", "VERDICT_REGRESSED", "VERDICT_INCONCLUSIVE",
    "ABLATION_VERDICTS",
    # admission（WO-0007 件 2：准入记录 + skill-pack 外发）
    "AdmissionLedger", "AdmissionRecord", "export_to_skillpack", "guardrail_verdict_of",
    "DECISION_ALLOWED", "DECISION_REJECTED", "DECISION_HELD", "ADMISSION_DECISIONS",
    # routes（便宜三件 Python 侧）
    "ArtifactRoute", "ArtifactRouteTable", "NodeCapacity",
    "SINK_GIT", "SINK_MINIO", "SINK_EVAL_ASSETS",
    "KIND_CODE", "KIND_VIDEO", "KIND_EVAL", "PIPELINE_DEFAULT",
    "TRUST_TRUSTED", "TRUST_UNTRUSTED",
    # usage（计量四维度 + 租约-consumer 绑定，v2.0 §4.4 / W-04）
    "UsageEvent", "UsageLedger", "UsageSummary",
    "KIND_LLM_RELAY", "KIND_COMPUTE_SECONDS", "KIND_STORAGE_BYTES", "KIND_SANDBOX_SECONDS",
    "USAGE_KINDS",
    "LeaseConsumerBinding", "BindingLedger",
    "BINDING_ACTIVE", "BINDING_CUTOFF", "BINDING_REVOKED", "BINDING_STATES",
    "CUTOFF_DRY_RUN", "CUTOFF_ENFORCE", "CUTOFF_MODES",
    "REASON_LEASE_EXPIRED", "REASON_LEASE_REVOKED", "REASON_LEASE_LAPSED",
    "CutoffAction", "cutoff_due", "cutoff_plan",
    # selection（line 圈择优：§5.4 纯机器信号公式 + winner_ref，W-05 骨架）
    "SELECTION_SCOPE", "SELECTION_SIGNALS", "SIGNAL_WEIGHTS",
    "SIGNAL_EVAL", "SIGNAL_MUTATION", "SIGNAL_CONCISENESS",
    "SIGNAL_DIFF_CONSENSUS", "SIGNAL_BUDGET", "MAX_CANDIDATES",
    "SelectionCandidate", "SelectionResult", "SelectionError", "SelectionRejectedError",
    "selection_score", "select_winner",
    # escalation（升级阶梯 + 人类就绪包，v2.1 §4.7 / 工单 W-06）
    "ESCALATION_SCOPE", "LEVELS", "LEVEL_ROLE", "LEVEL_CAPABILITIES",
    "LEVEL_L0", "LEVEL_L1", "LEVEL_L2", "LEVEL_L3", "LEVEL_L4", "LEVEL_L5",
    "PROOF_LEVELS", "HARD_LIST", "HARD_MONEY", "HARD_LEGAL_TOS",
    "HARD_IRREVERSIBLE", "HARD_THEORY_APPROVAL",
    "StormGuard", "Escalation", "EscalationCase", "EscalationEvent",
    "EscalationLedger", "PermissionExpansionProposal",
    "ReadinessTask", "FrozenFact", "ReversibilityAssessment",
    "ReadinessPackage", "ReadinessPiece", "PIECE_KEYS",
    "PIECE_FACTS", "PIECE_CATEGORY", "PIECE_NO_SOLUTION", "PIECE_REVERSIBILITY",
    "render_readiness", "signature_for",
    "EscalationSchemaError", "EscalationStateError", "EscalationStormError",
    "EscalationRequiredError", "UnknownEscalationCaseError",
    # platform_tokens（平台 token 铸造器，v2.1 §4.5 / 工单 W-09）
    "TOKEN_TTL_CAP_SECONDS", "GITHUB_JWT_TTL_CAP_SECONDS", "PLATFORMS", "BAO_REF_PREFIX",
    "ESCALATION_KIND",
    "STATUS_ACTIVE", "STATUS_EXPIRED", "STATUS_REVOKED",
    "PlatformTokenMinter", "TokenRequest", "MintedToken",
    "GitHubAppInstallationFlow", "escalation_signal", "hard_list_readiness",
    "TokenMintError", "HardListEscalationError",
    "__version__",
]
